kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sampleapplication
  namespace: sandbox-env
spec:
  output:
    to:
      kind: DockerImage
      name: "{{ .Values.repository }}:{{ .Values.tag | default .Chart.AppVersion }}"
  strategy:
    type: Docker
    dockerStrategy:
      noCache: true
      env:
        - name: dctag
          value: vapt
        - name: appName
          value: "{{ .Values.environment.applicatonname }}"
          
  source:
    type: Binary
    binary: {}
  runPolicy: Serial